# Generated by Django 6.0.6 on 2026-09-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ سهم هر واحد (تومان)')),
                ('status', models.CharField(choices=[('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده')], default='unpaid', max_length=10, verbose_name='وضعیت پرداخت')),
                ('due_time', models.DateTimeField(blank=True, null=True, verbose_name='مهلت پرداخت')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور فاکتور')),
                ('factor_id', models.CharField(blank=True, max_length=34, null=True, unique=True, verbose_name='آیدی فاکتور')),
                ('factor_image', models.ImageField(blank=True, null=True, upload_to='factor_image/', verbose_name='تصویر رسید پرداخت')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='Building.buildingexpense', verbose_name='بابت هزینه')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='Building.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ واریزی (تومان)')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('tracking_code', models.CharField(max_length=100, unique=True, verbose_name='کد پیگیری بانکی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید مدیر'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت رسید')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Finance.invoice', verbose_name='برای فاکتور')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Building.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'پرداختی',
                'verbose_name_plural': 'پرداختی\u200cها',
            },
        ),
    ]
